apiVersion: v1
kind: Secret
metadata:
  name: db-secret-user
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://otus-user-postgresql:5432/user-service"
  SPRING_DATASOURCE_PASSWORD: "12345"
  SPRING_DATASOURCE_USERNAME: "pguser"