apiVersion: v1
kind: Secret
metadata:
  name: db-secret-auth
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://otus-auth-postgresql:5432/auth-service"
  SPRING_DATASOURCE_PASSWORD: "12345"
  SPRING_DATASOURCE_USERNAME: "pguser"