apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-gateway
  labels:
    app: spring-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-gateway
  template:
    metadata:
      labels:
        app: spring-gateway
    spec:
      containers:
        - name: gateway
          image: jen1g/otus-gateway:v12
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: spring-config-auth
                  key: jwt.secret
          ports:
            - containerPort: 8080