spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://otus-auth-service.default.svc.cluster.local
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: user-service-open
          uri: http://otus-user-service.default.svc.cluster.local
          predicates:
            - Path=/user
          # Здесь фильтры можно оставить без изменений

        - id: user-service-secure
          uri: http://otus-user-service.default.svc.cluster.local
          predicates:
            - Path=/user/**
          filters:
            - CheckAuthToken  # Удалили RemoveRequestHeader
