apiVersion: v1
kind: Service
metadata:
  name: spring-gateway
  namespace: default
spec:
  selector:
    app: spring-gateway
  ports:
    - protocol: TCP
      port: 80       # Порт для внешнего доступа
      targetPort: 8080  # Порт, на котором запущен Gateway в контейнере
  type: ClusterIP